name: Deploy Docs to PaaS
on: [push]
jobs:
  deploy-to-paas:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install cf client
        env:
          CF_CLI_DOWNLOAD_URL: https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github&version=v7
        run: |
          echo "::group:: Download cf CLI"
          curl -sL ${CF_CLI_DOWNLOAD_URL} | sudo tar -zx -C /usr/local/bin
          cf version
          echo "::endgroup::"
      - name: cf login
        shell: bash
        run: |
          cf api ${CF_API_URL}
          cf auth
          cf target -o ${CF_ORG_NAME} -s ${CF_SPACE_NAME}
        env:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_SPACE_NAME: docs
          CF_ORG_NAME: gds-digital-identity-authentication
          CF_API_URL: https://api.london.cloud.service.gov.uk

      - name: Build
        run: bundle exec middleman build
      - name: Push to PaaS
        run: cf push
